model                  = gpt-5.1-codex-max
model_reasoning_effort = medium

[features]
; allow the model to request web searches
web_search_request = true
view_image_tool    = true
; for mcp auth
rmcp_client        = true

[mcp_servers.incidentio]
command = /home/gabriel/sync/Travail/Repo/incidentio-mcp-golang/start-mcp-server.sh

[mcp_servers.incidentio.env]
INCIDENT_IO_API_KEY = ENC[AES256_GCM,data:tzw/n+4BjQsI4EsB2ftoA2ZOugKtpCZOjYLH+w3HEoQJ3iszDgef2EeSSULR3SIMnu7CWIqgVUhr7MFuJFpA3OMkyiY=,iv:4akaMHFwL6XANdS1zMrDg9wBENWIwwgKPWBSqB8OWyM=,tag:Afx9n5xUtiqVtTmThS7E2g==,type:str]

[mcp_servers.auth0]
command = /usr/bin/npx
args    = ["-y", "@auth0/auth0-mcp-server", "run"]

[mcp_servers.auth0.env]
DEBUG                    = auth0-mcp
DISPLAY                  = :1
DBUS_SESSION_BUS_ADDRESS = unix:path=/run/user/1000/bus

[projects."/home/gabriel/sync/Travail/Repo/opstrom-config-updater"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/indexer-argocd"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/flux-monitor"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/incident-ops"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/k8s-opstrom"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/opstrom-agent"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/local-ops"]
trust_level = trusted

[projects."/home/gabriel"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/indexer"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/utils"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/operator"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/utility-scripts"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/codex"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/k8s-ops-infra"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/label-aggregator"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/k8s-pinax-infra"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/infradao-argocd"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/project-automation"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/home"]
trust_level = trusted

[projects."/home/gabriel/sync/Travail/Repo/graph-horizon-tools"]
trust_level = trusted

[notice]
hide_gpt5_1_migration_prompt            = true
hide_gpt-5.1-codex-max_migration_prompt = true

[sops]
age__list_0__map_recipient = age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6
age__list_0__map_enc       = -----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYUlTZDdxaEhxWkRVVmZk\na0tpYWJPVUpuNTJDRkFiNWpEVlZTZ3Y4S2l3CmxkWFVUYUlVYk8ycTFkREdVaWhJ\nUHdtT1k3cC9GUWNuU043OUVuV0JpY0EKLS0tIDhYczk0OXJGb0ZFUXlrbEpJOUdp\nczZmejJtaC80Q21rTVI5RnZZMm9RRkUKj4IPDeQlT7ZMPijpYqsUUD5LZw8a8S1b\nROdl/bpp1zfektFGSQAwsT+In+xMgArKn+yKF8V2DRQ+FSkQVWiHIQ==\n-----END AGE ENCRYPTED FILE-----\n
lastmodified               = 2025-12-05T00:19:17Z
mac                        = ENC[AES256_GCM,data:pDzroE0zmvKMXwzlEb3oS4qH5Hq4/h+K3FLcBg6KYSp1L/Q1SqLMTZX3KfjEfU6wdmxE5nVzR9leNHFRPXkgdYdlGkTw/DLL6MDR0xxqNRQWb9BzFhwMjvgEhN7vw1j6K9WfdtVpj86yqsYX92cyz9iQS9ujl7j7qYlVaIZy+hs=,iv:6E87GdLG/OWYd45U2ghxOIrrPJzkbBH0pCC5AMYgCo8=,tag:q3o8dlPoCrk94qET4euhMg==,type:str]
encrypted_regex            = ^(INCIDENT_IO_API_KEY)$
version                    = 3.11.0
